name: Update NanoCLR Dependencies Daily
on:
  schedule:
  - cron:  '00 00 * * *'
  repository_dispatch:
    types: update-dependencies

defaults:
  run:
    shell: pwsh

jobs:
  Update:
    name: Update NanoCLR dependencies
    timeout-minutes: 15
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update dependencies
        uses: nanoframework/nanodu@v1
        with:
          stablePackages: true
          branchToPr: 'develop'
          solutionsToCheck: './src/Bytewizer.NanoCLR.Runtime.sln'